name: create-a-docker
on:
  push:
    branches:
      - master

jobs:
  makeodocker:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: buildx setup
        uses: docker/setup-buildx-action@v2
      -
        name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
      -
        name: build and push this crap
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ghcr.io/hakushigo/goexample